/*============================================================================*/
/*
  VFLib: https://github.com/vinniefalco/VFLib

  Copyright (C) 2008 by Vinnie Falco <vinnie.falco@gmail.com>

  This library contains portions of other open source products covered by
  separate licenses. Please see the corresponding source files for specific
  terms.
  
  VFLib is provided under the terms of The MIT License (MIT):

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
  IN THE SOFTWARE.

  Based on SOCI - The C++ Database Access Library: 

  SOCI: http://soci.sourceforge.net/

    This file incorporates work covered by the following copyright
    and permission notice:

    Copyright (C) 2004 Maciej Sobczak, Stephen Hutton, Mateusz Loskot,
    Pawel Aleksander Fedorynski, David Courtney, Rafal Bobrowski,
    Julian Taylor, Henning Basold, Ilia Barahovski, Denis Arnaud,
    Daniel Lidström, Matthieu Kermagoret, Artyom Beilis, Cory Bennett,
    Chris Weed, Michael Davidsaver, Jakub Stachowski, Alex Ott, Rainer Bauer,
    Martin Muenstermann, Philip Pemberton, Eli Green, Frederic Chateau,
    Artyom Tonkikh, Roger Orr, Robert Massaioli, Sergey Nikulov,
    Shridhar Daithankar, Sören Meyer-Eppler, Mario Valesco.

    Boost Software License - Version 1.0, August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/
/*============================================================================*/

#ifndef VF_DB_SESSION_VFHEADER
#define VF_DB_SESSION_VFHEADER

namespace db {

/*============================================================================*/
/**
  @brief A session for the embedded database.

  @ingroup vf_db
*/
class session
{
public:
  session ();
  ~session ();

  // DEPRECATED!
  // opens the deferred clone
  explicit session (session const& deferredClone);
  Error clone ();

/**
  Open a database.
      
  The database at the specified path is opened. The connection string is
  a set of "{key}={value}" pairs separated with the pipe symbol ('|').
  Choices for key and value are:

  @code

  timeout = (number) || "infinite"

  mode    = "read" || "write" || "create"

  cache   = "shared" || "private"

  threads = "single" || "multi"

  @endcode
*/
  Error open (String fileName,
              std::string options = "timeout=infinite|mode=create|threads=multi");
  
  void close ();

  void begin ();
  Error commit ();
  void rollback ();

  bool in_transaction ()
  {
    return m_bInTransaction;
  }

  detail::once_type once (Error& error);
  detail::prepare_type prepare;

  rowid last_insert_rowid();

  std::ostringstream& get_query_stream();

  void log_query(std::string const& query);

  void set_got_data(bool bGotData);
  bool got_data() const;

  sqlite3* get_connection()
  {
    return m_connection;
  }

private:
  Error hard_exec (std::string const& query);

private:
  class Sqlite3;
  ReferenceCountedObjectPtr <Sqlite3> m_instance;

  sqlite3* m_connection;
  String m_fileName;
  std::string m_connectString;
  bool m_bInTransaction;
  std::ostringstream m_query_stream;
  bool m_bGotData;
};

}

#endif
